### ISSUE TITLE
Multiple emails sent

### ISSUE THREAD

**Issue by Dutch-guy** [ingpsp/opencart#5]
I'm migrating an OpenCart webshop from 1.5.6.4 to 2.3.0.2

At the momet we are using a different extension for ING Kassa Compleet. This works fine. However that extension is not suitable for OpenCart 2.3.0.2

I am now testing with this extension version 1.40.

But I'm experiencing some trouble with the mails that are being sent to the customer. When an order has been placed the client receives 3 mails instead of just one. two "in process" mails and one mail with the final status.

Any idea how to fix this? It does this with all payment types.

**Comment by mgsander** [comment]
Hi, I believe the issue lies in the [`processWebhook`](https://github.com/ingpsp/opencart/blob/db89cb5e92e976d80b9f666051c523d5b28f6ab7/upload/system/library/inghelper.php#L287) method of the `IngHelper` class (in `upload/system/library/inghelper.php`). It calls OpenCart's `addOrderHistory` method, with the `$notify` parameter always set to true. Since each payment goes through at least three status changes (`null` → `new`, `new` → `processing`, `processing` → `completed`), OpenCart might send emails for all of these updates. Furthermore, our platform can send events to the webhook endpoint for updates that do not change the status, and I'm not quite sure how OpenCart handles this.

We will check if we can improve behaviour in this regard, but in the mean time, could you please try to patch the `processWebhook` method by not sending notifications for the `new` status?

For example:
```php
    /**
     * Method processes calls to webhook url
     *
     * @param object $paymentMethod
     * @param array $webhookData
     * @return void
     */
    public function processWebhook($paymentMethod, array $webhookData)
    {
        if ($webhookData['event'] == 'status_changed') {
            $ingOrder = $paymentMethod->ing->getOrder($webhookData['order_id']);
            $orderInfo = $paymentMethod->model_checkout_order->getOrder($ingOrder->getMerchantOrderId());
            $notify = $ingOrder->getStatus() != 'new'; // don't send notifications for status "new"
            if ($orderInfo) {
                $paymentMethod->model_checkout_order->addOrderHistory(
                    $ingOrder->getMerchantOrderId(),
                    $paymentMethod->ingHelper->getOrderStatus($ingOrder->getStatus(), $paymentMethod->config),
                    'Status changed for order: '.$ingOrder->id()->toString(),
                    $notify
                );
            }
        }
    }
```

**Comment by Dutch-guy** [comment]
Hi,

Unfortunately it is not working.

It sill sends 3 e-mails in total.

This looks like this:

[cid:image003.jpg@01D3E08B.B4BCE2B0]

These 2 emails are already sent when clicking on the order button, so at that point it isn’t even certain that the customer will pay.

I checked and “$ingOrder->getStatus” gives me on the first mail nothing and on the second mail a “1” as response.

What also is a problem is that the status “iDeal betaalt, In behandeling” is my final status on which it generates an invoice number and attaches the PDF invoice. But at that point it isn’t even certain that the customer will pay.

Please advice.

Van: Maarten Sander [mailto:notifications@github.com]
Verzonden: maandag 30 april 2018 11:13
Aan: ingpsp/opencart <opencart@noreply.github.com>
CC: Raymond de Vries | Think Twice <info@thinktwice.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [ingpsp/opencart] Multiple emails sent (#5)


Hi, I believe the issue lies in the processWebhook<https://github.com/ingpsp/opencart/blob/db89cb5e92e976d80b9f666051c523d5b28f6ab7/upload/system/library/inghelper.php#L287> method of the IngHelper class (in upload/system/library/inghelper.php). It calls OpenCart's addOrderHistory method, with the $notify parameter always set to true. Since each payment goes through at least three status changes (null → new, new → processing, processing → completed), OpenCart might send emails for all of these updates. Furthermore, our platform can send events to the webhook endpoint for updates that do not change the status, and I'm not quite sure how OpenCart handles this.

We will check if we can improve behaviour in this regard, but in the mean time, could you please try to patch the processWebhook method by not sending notifications for the new status?

For example:

    /**

     * Method processes calls to webhook url

     *

     * @param object $paymentMethod

     * @param array $webhookData

     * @return void

     */

    public function processWebhook($paymentMethod, array $webhookData)

    {

        if ($webhookData['event'] == 'status_changed') {

            $ingOrder = $paymentMethod->ing->getOrder($webhookData['order_id']);

            $orderInfo = $paymentMethod->model_checkout_order->getOrder($ingOrder->getMerchantOrderId());

            $notify = $ingOrder->getStatus() != 'new'; // don't send notifications for status "new"

            if ($orderInfo) {

                $paymentMethod->model_checkout_order->addOrderHistory(

                    $ingOrder->getMerchantOrderId(),

                    $paymentMethod->ingHelper->getOrderStatus($ingOrder->getStatus(), $paymentMethod->config),

                    'Status changed for order: '.$ingOrder->id()->toString(),

                    $notify

                );

            }

        }

    }
